// Generated by scripts/generate-release-changelog.mjs. Do not hand-edit release builds.
// The committed version is a safe local/unreleased fallback; the release workflow replaces it before Vite runs.
export const GENERATED_CHANGELOG_SCHEMA_VERSION = 1 as const;
export const GENERATED_CHANGELOG_ENTRIES = [
  {
    "version": "v0.1.0-14",
    "releasedAt": "2026-08-08T01:15:09.000Z",
    "commit": "5265d74a7f428f014be7fa08a5847c676efdad82",
    "changes": [
      "Integration: Merge pull request #4 from Ding-Ding-Projects/claude/ultracode-opus-agents-s59hks"
    ]
  },
  {
    "version": "v0.1.0-13",
    "releasedAt": "2026-08-07T18:09:39.000Z",
    "commit": "b4a94f3e64ee30d9b72d0c440267d765ebd8b6ee",
    "changes": [
      "Documentation: Fix site/assets/app.css content corrupted by a prior double-base64-encoded API push"
    ]
  },
  {
    "version": "v0.1.0-9",
    "releasedAt": "2026-08-07T18:06:26.000Z",
    "commit": "60d4aaabf2474bad0b38d860be980fb43b2681db",
    "changes": [
      "Documentation: Fix HANDOFF.md content corrupted by a prior double-base64-encoded API push"
    ]
  },
  {
    "version": "v0.1.0-8",
    "releasedAt": "2026-08-07T17:41:11.000Z",
    "commit": "4b140cdc6397b716ad76f1c7219061855e8dd96f",
    "changes": [
      "Documentation: Style select/range on the docs site to match MD3 too"
    ]
  },
  {
    "version": "v0.1.0-7",
    "releasedAt": "2026-08-07T17:37:18.000Z",
    "commit": "e1ebe28f95799a4db1aa4ac17e30feb03d1ef747",
    "changes": [
      "Interface: Replace native OS controls with MD3-styled select/range/checkbox"
    ]
  },
  {
    "version": "v0.1.0-6",
    "releasedAt": "2026-08-07T17:23:01.000Z",
    "commit": "183ce737b6661d92cc4caae42a123c0e8cebb396",
    "changes": [
      "Documentation: Fix mobile clipping: hide palette kbd hints and wrap settings labels under narrow widths"
    ]
  },
  {
    "version": "v0.1.0-4",
    "releasedAt": "2026-08-07T17:19:37.000Z",
    "commit": "492c9ef79115348847d3490836426fed048921b9",
    "changes": [
      "Documentation: Fix mobile clipping on the Pages site; confirm Pages is live"
    ]
  },
  {
    "version": "v0.1.0-3",
    "releasedAt": "2026-08-07T16:45:12.000Z",
    "commit": "459f3b9f850c42dd9aca932aef06be5af1aa917a",
    "changes": [
      "Documentation: Record real CI/release/Pages evidence"
    ]
  },
  {
    "version": "v0.1.0-2",
    "releasedAt": "2026-08-07T16:41:28.000Z",
    "commit": "468566de96d8fdee150cfaf24b860724ff6526a9",
    "changes": [
      "Delivery: Fix Pages deploy: enable Pages via configure-pages action"
    ]
  },
  {
    "version": "v0.1.0-1",
    "releasedAt": "2026-08-07T16:35:52.000Z",
    "commit": "4ad8430385cf4950b3c386fb35f97f45649fffaa",
    "changes": [
      "Interface: Real local operation history, CI, unsigned Squirrel release, and GitHub Pages (#3)"
    ]
  }
] as const;
export const GENERATED_RELEASE_MANIFEST = {
  "schemaVersion": 1,
  "repository": "Ding-Ding-Projects/ding-ding-app-store",
  "generatedAt": "2026-08-08T01:15:09.000Z",
  "entries": [
    {
      "version": "v0.1.0-14",
      "releasedAt": "2026-08-08T01:15:09.000Z",
      "commit": "5265d74a7f428f014be7fa08a5847c676efdad82",
      "changes": [
        "Integration: Merge pull request #4 from Ding-Ding-Projects/claude/ultracode-opus-agents-s59hks"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-14",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-13",
      "releasedAt": "2026-08-07T18:09:39.000Z",
      "commit": "b4a94f3e64ee30d9b72d0c440267d765ebd8b6ee",
      "changes": [
        "Documentation: Fix site/assets/app.css content corrupted by a prior double-base64-encoded API push"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-13",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-9",
      "releasedAt": "2026-08-07T18:06:26.000Z",
      "commit": "60d4aaabf2474bad0b38d860be980fb43b2681db",
      "changes": [
        "Documentation: Fix HANDOFF.md content corrupted by a prior double-base64-encoded API push"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-9",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-8",
      "releasedAt": "2026-08-07T17:41:11.000Z",
      "commit": "4b140cdc6397b716ad76f1c7219061855e8dd96f",
      "changes": [
        "Documentation: Style select/range on the docs site to match MD3 too"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-8",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-7",
      "releasedAt": "2026-08-07T17:37:18.000Z",
      "commit": "e1ebe28f95799a4db1aa4ac17e30feb03d1ef747",
      "changes": [
        "Interface: Replace native OS controls with MD3-styled select/range/checkbox"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-7",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-6",
      "releasedAt": "2026-08-07T17:23:01.000Z",
      "commit": "183ce737b6661d92cc4caae42a123c0e8cebb396",
      "changes": [
        "Documentation: Fix mobile clipping: hide palette kbd hints and wrap settings labels under narrow widths"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-6",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-4",
      "releasedAt": "2026-08-07T17:19:37.000Z",
      "commit": "492c9ef79115348847d3490836426fed048921b9",
      "changes": [
        "Documentation: Fix mobile clipping on the Pages site; confirm Pages is live"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-4",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-3",
      "releasedAt": "2026-08-07T16:45:12.000Z",
      "commit": "459f3b9f850c42dd9aca932aef06be5af1aa917a",
      "changes": [
        "Documentation: Record real CI/release/Pages evidence"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-3",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-2",
      "releasedAt": "2026-08-07T16:41:28.000Z",
      "commit": "468566de96d8fdee150cfaf24b860724ff6526a9",
      "changes": [
        "Delivery: Fix Pages deploy: enable Pages via configure-pages action"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-2",
      "publicationState": "published",
      "dimSum": null
    },
    {
      "version": "v0.1.0-1",
      "releasedAt": "2026-08-07T16:35:52.000Z",
      "commit": "4ad8430385cf4950b3c386fb35f97f45649fffaa",
      "changes": [
        "Interface: Real local operation history, CI, unsigned Squirrel release, and GitHub Pages (#3)"
      ],
      "releaseUrl": "https://github.com/Ding-Ding-Projects/ding-ding-app-store/releases/tag/v0.1.0-1",
      "publicationState": "published",
      "dimSum": null
    }
  ]
} as const;
